<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="F_TurboGateValve_Protection_ILK_Turbo_OFF_OK_NO_GPI_READ" Id="{f9959c0d-1ae4-44b1-8bdf-95dc0eacb385}" SpecialFunc="None">
    <Declaration><![CDATA[(* This Function Block evaluates the ILK condition of the Turbo Gate valve *)
(* The logic Protects the Turbo pump from inlet pressure above the SP*)
(* And Protects the Turbo pump from backing pressure above the SP*)
FUNCTION F_TurboGateValve_Protection_ILK_Turbo_OFF_OK_NO_GPI_READ : BOOL
VAR_INPUT
    i_Turbo : ST_PTM; // Turbo Pump
    i_stISG : ST_VG; //Gauge measuring inlet Pressure e.g Pirani
    i_stBSG : ST_VG; //Gauge measuring backing Pressure e.g Pirani
    ScrollPump	:	ST_RoughPump; // Roughing pump
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_TurboGateValve_Protection_ILK_Turbo_OFF_OK_NO_GPI_READ := (i_stBSG.xPRESS_OK AND i_stBSG.rPRESS < i_Turbo.rBackingPressureSP)
                        AND (ScrollPump.eState = pumpRUNNING);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>