<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{9edaa357-6cfe-4c1d-9d92-d5e78575201a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
PRG_Chamber_Gauges();

PRG_Chamber_Valves();

PRG_Chamber_Pumps();

PRG_Mechanical_Room();

PRG_VLS_VACUUM();

//PRG_ADS_Gauges();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="3" Count="7" />
      <LineId Id="16" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>