<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_LI3K2" Id="{ac208cdc-02fb-4676-8502-445d3aa00a8a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PRG_LI3K2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
RIX_LI3K2_PTM_01(i_xExtILKOk:=TRUE, // Check logic; probably need to confirm roughing valve is open, pump is on?
                 iq_stPtm=>);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>