<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_Chamber_Gauges" Id="{cf1bb2d6-ee0f-41b1-a857-33af2cd32803}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Chamber_Gauges
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
CMC_GPI_01.M_SetBits(30518);
CMC_GPI_01(PG=>stCMC_GPI_01);

(*
CRIX_GPI_02.M_SetBits(30518);
CRIX_GPI_02(PG=>stCRIX_GPI_02);

CRIX_GPI_03.M_SetBits(30518);
CRIX_GPI_03(PG=>stCRIX_GPI_03);

CRIX_GPI_04.M_SetBits(30518);
CRIX_GPI_04(PG=>stCRIX_GPI_04);
*)

ROUGH_GPI_01.M_SetBits(30518);
ROUGH_GPI_01(PG=>stROUGH_GPI_01);

CMC_GCC_01.M_SetBits(30518);
CMC_GCC_01(PG:=CMC_GPI_01.PG,
			IG=>stCMC_GCC_01);


CRYO_GCP_02.M_SetBits(30518);
CRYO_GCP_02(PG=>stCRYO_GCP_02);

CRYO_GCP_01.M_SetBits(30518);
CRYO_GCP_01(PG=>stCRYO_GCP_01);


SDS_GCP_01.M_SetBits(30518);
SDS_GCP_01(PG=>);

CMC_GCP_01.M_SetBits(30518);
CMC_GCP_01(PG=>stCMC_GCP_01);]]></ST>
    </Implementation>
    <LineIds Name="PRG_Chamber_Gauges">
      <LineId Id="3" Count="33" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>